spring:
  application:
    name: social-network
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#  datasource:
#    url: jdbc:mysql://localhost/social-network?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
#    username: root
#    password: 123456789
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
#        storage_engine: innodb

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-209-61-239.compute-1.amazonaws.com:5432/d26ij6tn5c5pv3
    username: xxsufefscsafro
    password: d6213803eb258a41b25e553dee193b1107421e3c9744aaa8271499f68ef652ef
  data:
    cassandra:
      schema-action: create_if_not_exists
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: ${SOCIAL_NETWORK_PORT:9999}
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

jwt:
  secret: 540E772F66BCAF43C9BE3E3DA90F31BBA8C738884C9B3AAF7CE4FED15DCFC7E7
  expirationDateInMs: 18000000

cloudinary:
  cloud_name: ahihi
  api_key: 268736226145353
  api_secret: BODd_eO3cqqHh0p4KPdS0GH0HPU

application:
  version: ${VERSION:1.0}
  swagger:
#    base-uri: localhost
    base-uri: https://social-network-ados.herokuapp.com/
